--------------------------------------------------------
--  File created - Tuesday-January-17-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "ECOM"."MANAGER" 
   (	"ID" NUMBER, 
	"FULLNAME" VARCHAR2(55 BYTE), 
	"DOB" VARCHAR2(55 BYTE), 
	"AGE" VARCHAR2(55 BYTE), 
	"EMAIL" VARCHAR2(55 BYTE), 
	"MOBNO" VARCHAR2(55 BYTE), 
	"PASSWORD" VARCHAR2(55 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOM"."MANAGER_PK" ON "ECOM"."MANAGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MANAGER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."MANAGER_TRG" 
BEFORE INSERT ON MANAGER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."MANAGER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MANAGER_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."MANAGER_TRG1" 
BEFORE INSERT ON MANAGER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MANAGER_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."MANAGER_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "ECOM"."MANAGER" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ECOM"."MANAGER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."MANAGER" MODIFY ("MOBNO" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."MANAGER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."MANAGER" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."MANAGER" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."MANAGER" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."MANAGER" MODIFY ("ID" NOT NULL ENABLE);
