--------------------------------------------------------
--  File created - Tuesday-January-17-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "ECOM"."ORDER_DETAILS" 
   (	"ID" NUMBER, 
	"ORDER_ID" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADRESS" VARCHAR2(100 BYTE), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(100 BYTE), 
	"PRICE" VARCHAR2(100 BYTE), 
	"PAYMENT" VARCHAR2(100 BYTE), 
	"CID" NUMBER, 
	"STASTUS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDER_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOM"."ORDER_DETAILS_PK" ON "ECOM"."ORDER_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ORDER_DETAILS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."ORDER_DETAILS_TRG" 
BEFORE INSERT ON ORDER_DETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."ORDER_DETAILS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDER_DETAILS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."ORDER_DETAILS_TRG1" 
BEFORE INSERT ON ORDER_DETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."ORDER_DETAILS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDER_DETAILS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."ORDER_DETAILS_TRG2" 
BEFORE INSERT ON ORDER_DETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."ORDER_DETAILS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDER_DETAILS_TRG3
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."ORDER_DETAILS_TRG3" 
BEFORE INSERT ON ORDER_DETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ORDER_DETAILS_SEQ3.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."ORDER_DETAILS_TRG3" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("STASTUS" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" ADD CONSTRAINT "ORDER_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("PAYMENT" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."ORDER_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
