--------------------------------------------------------
--  File created - Tuesday-January-17-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "ECOM"."PRODUCT" 
   (	"PID" NUMBER, 
	"PNAME" VARCHAR2(500 BYTE), 
	"PCATEGORY" VARCHAR2(80 BYTE), 
	"PSUBCATEGORY" VARCHAR2(80 BYTE), 
	"PPRICE" VARCHAR2(80 BYTE), 
	"PCOLOR" VARCHAR2(80 BYTE), 
	"PIMAGE" VARCHAR2(80 BYTE), 
	"PDECS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECOM"."PRODUCT_PK" ON "ECOM"."PRODUCT" ("PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."PRODUCT_TRG1" 
BEFORE INSERT ON PRODUCT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."PRODUCT_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."PRODUCT_TRG" 
BEFORE INSERT ON PRODUCT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."PRODUCT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECOM"."PRODUCT_TRG2" 
BEFORE INSERT ON PRODUCT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PID IS NULL THEN
      SELECT PRODUCT_SEQ3.NEXTVAL INTO :NEW.PID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECOM"."PRODUCT_TRG2" ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "ECOM"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ECOM"."PRODUCT" MODIFY ("PIMAGE" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."PRODUCT" MODIFY ("PPRICE" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."PRODUCT" MODIFY ("PCATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."PRODUCT" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "ECOM"."PRODUCT" MODIFY ("PID" NOT NULL ENABLE);
